### ISSUE TITLE
DL.eval error

### ISSUE THREAD

**Issue by yiwenCao92** [pylayers/pylayers#284]
Hello.After completing the set up of the pylayers in win8(following the step in github), I tested the DL.eval() .An error occured:

DL.eval()

AttributeErrorTraceback (most recent call last)
<ipython-input-3-a6148ad24689> in <module>()
----> 1 DL.eval()

D:\Anaconda2\lib\site-packages\pylayers-0.5-py2.7.egg\pylayers\simul\link.pyc in eval(self, **kwargs)
   1628         tic = time.time()
   1629         Si = Signatures(self.L,
-> 1630                         self.ca,
   1631                         self.cb,
   1632                         cutoff=kwargs['cutoff'],

D:\Anaconda2\lib\site-packages\pylayers-0.5-py2.7.egg\pylayers\simul\link.pyc in ca(self)
    523     @property
    524     def ca(self):
--> 525         return self._ca
    526 
    527     @property

AttributeError: 'DLink' object has no attribute '_ca'

Then I unistalled Anaconda，and installed it again.Now I occured "Key error 'GASS'"when I type'DL=DLink()'.Can you help me fix the problem?Many  thanks

**Comment by niamiot** [comment]
About the "Key error 'GASS'" error :

One thing to understand is : When you install PyLayers for the first time, data are copied from the data directory of the pylayers source to your project directory. The 2 directories path can be found into ".pylayers" file (hidden file) at the root of your HOME directory.
All the commit only update the PyLayers data directory and not your project directory. So e.g. any changes on '.ini' files by commit must be manually copied to your how project directory.

The files **SlabDB.ini** & **MatDB.ini** are corrupted **in your PyLayers_project/ini directory (** due to a past corruption in a commit from our side).
you may solve the problem by **replacing** the 2 files  with those from the **<PyLayers_sources_directory>/data/ini.**
This will solve the isssue

**Comment by yiwenCao92** [comment]
Many thanks!
